<?php

DEFINE('ERROR_CODE_USER_NOT_FOUND',       1000);
DEFINE('ERROR_CODE_INVALID_PARAMETERS',   1001);
DEFINE('ERROR_CODE_WRONG_PASSWORD',       1002);
DEFINE('ERROR_CODE_NO_ENCRYPTED_FILES',   1003);