<?php

DEFINE('ERROR_CODE_USER_NOT_FOUND',       1000);
DEFINE('ERROR_CODE_INVALID_PARAMETERS',   1001);
DEFINE('ERROR_CODE_WRONG_PASSWORD',       1002);
DEFINE('ERROR_CODE_NO_ENCRYPTED_FILES',   1003);
DEFINE('ERROR_CODE_FRIENDSHIP_NOT_FOUND', 1004);
DEFINE('ERROR_CODE_ALLREADY_FRIEND',      1005);

DEFINE('UPLOAD_PATH',   'uploads/');
DEFINE('SPLITTER',      "_-|-_");

DEFINE('USER_MESSAGE_SUCCESS', 0);
DEFINE('USER_MESSAGE_WARNING', 1);
DEFINE('USER_MESSAGE_ERROR', 2);